### ISSUE TITLE
Updating local continent database - 301 Moved Permanently

### ISSUE THREAD

**Issue by rjp2525** [Torann/laravel-geoip#102]
Visiting the [link used for updating the local continent data](https://github.com/Torann/laravel-geoip/blob/master/src/Services/IPApi.php#L100) in the browser will download the `country_continent.csv` file, but running `php artisan geoip:update` leaves an empty array within `continents.json` in the app storage folder. Debugging and retrieving the output returns a 301 Moved Permanently response from maxmind:

```json
[
    "<html><head><title>301 Moved Permanently<\/title><\/head>\r\n<body bgcolor=\"white\">\r\n<center><h1>301 Moved Permanently<\/h1><\/center>\r\n<hr><center>nginx<\/center>\r\n<\/body>\r\n<\/html>\r\n",
    {
        "0":"HTTP\/1.1 301 Moved Permanently",
        "Server":"nginx",
        "Date":"Sun, 25 Feb 2018 20:16:06 GMT",
        "Content-Type":"text\/html",
        "Content-Length":"178",
        "Connection":"keep-alive",
        "Keep-Alive":"timeout=20",
        "Location":"https:\/\/dev.maxmind.com\/static\/csv\/codes\/country_continent.csv",
        "X-Type":"default",
        "1":"",
        "2":""
    }
]
```

**Comment by rjp2525** [comment]
I was able to fix within a custom service by using `file_get_contents` rather than `$this->client->get()` and changing `$lines = explode("\n", $data[0]);` to `$lines = explode("\n", $data);`:

```php
public function update()
{
    $data = file_get_contents('http://dev.maxmind.com/static/csv/codes/country_continent.csv');

    // Verify server response
    if ($this->client->getErrors() !== null) {
        throw new Exception($this->client->getErrors());
    }

    $lines = explode("\n", $data);

    array_shift($lines);

    ....
}
```

**Comment by Torann** [comment]
The download file for this is in the config file
