### ISSUE TITLE
Torann\GeoIP\Support\curl_init()

### ISSUE THREAD

**Issue by rezasys2** [Torann/laravel-geoip#113]
Hello
I'm trying to install this extension to use geoIp. But this command give me 404 error.

Get:1 https://packages.sury.org/php/ jessie/main php7.2-common amd64 7.2.3-1+0~20180306120140.19+jessie~1.gbp81bf3b [546 kB]
Err https://packages.sury.org/php/ jessie/main php7.2-common amd64 7.2.3-1+0~20180306120140.19+jessie~1.gbp81bf3b
  HttpError404
Get:2 https://packages.sury.org/php/ jessie/main php7.2-curl amd64 7.2.3-1+0~20180306120140.19+jessie~1.gbp81bf3b [27.8 kB]
Err https://packages.sury.org/php/ jessie/main php7.2-curl amd64 7.2.3-1+0~20180306120140.19+jessie~1.gbp81bf3b
  HttpError404
Get:3 https://packages.sury.org/php/ jessie/main php-curl all 1:7.2+59+0~20180122053933.6+jessie~1.gbp70c3ba [5,716 B]
Err https://packages.sury.org/php/ jessie/main php-curl all 1:7.2+59+0~20180122053933.6+jessie~1.gbp70c3ba
  HttpError404
Err http://security.debian.org/ jessie/updates/main libcurl3 amd64 7.38.0-4+deb8u10
  404  Not Found [IP: 212.211.132.250 80]
E: Failed to fetch http://security.debian.org/pool/updates/main/c/curl/libcurl3_7.38.0-4+deb8u10_amd64.deb  404  Not Found [IP: 212.211.132.250 80]

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.2/php7.2-common_7.2.3-1+0~20180306120140.19+jessie~1.gbp81bf3b_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php7.2/php7.2-curl_7.2.3-1+0~20180306120140.19+jessie~1.gbp81bf3b_amd64.deb  HttpError404

E: Failed to fetch https://packages.sury.org/php/pool/main/p/php-defaults/php-curl_7.2+59+0~20180122053933.6+jessie~1.gbp70c3ba_all.deb  HttpError404

**Comment by rezasys2** [comment]
Solved problem , another question how can I get list of this api states. I need the words .

**Comment by Torann** [comment]
I have no clue what you're asking

**Comment by rezasys2** [comment]
I need a list of state_name . I'm going to compare this text with my database texts. So I should know what are your names.

**Comment by Torann** [comment]
That's not part of this package. It is only used to look up geo data for an IP address.
