### ISSUE TITLE
This cache store does not support tagging

### ISSUE THREAD

**Issue by tontonAurel** [Torann/laravel-geoip#123]
When updated torann/geoip from 1.0.7 to 1.0.8 i got this error : `This cache store does not support tagging`. I use file as cache driver and my version of laravel is 5.6.38

**Comment by tontonAurel** [comment]
Sry i think it the same that this one #89

**Comment by brentscholl** [comment]
I also have the same problem after updating from 1.0.7 to 1.0.8

**Comment by blyleven** [comment]
Use redis for caching

**Comment by tontonAurel** [comment]
Yes, i'm agree with you but it's minor update (from 1.0.7 to 1.0.8), it should not break the application since we didn't change anything else

**Comment by codepandit** [comment]
I have a same issue, no matter what I try It doesn't work. I'm using Laravel 5.7 and geoip 1.0.8

**Comment by rappasoft** [comment]
Agreed, I have cache set to none and it still happens.

**Comment by briansrepo** [comment]
I had commented out the cache_tags line when I first installed the package a year ago for this exact reason, and it's been working fine with file-based caching.


`//'cache_tags' => ['torann-geoip-location'],`


This update broke it. So what specifically changed is that now `cache_tags` defaults to on instead of off. Instead of commenting out that line, you now need to explicitly set cache_tags to false or null, like @rappasoft said.


`'cache_tags' => false,`

**Comment by tiznull** [comment]
This is how I fixed the problem
#Setup for GEOIP
> Open up config/geoip.php

##Tasks for GEOIP
-[ ] Change the service to 'maxmind_database'
-[ ] Change the cache tags to a more dynamic method of handling the environment.

> Setup the service
```php
    service' => 'maxmind_database',
```
> Change the Cache Tags
```php
    'cache_tags' => env('CACHE_DRIVER', 'array') === "file" ? null : ['torann-geoip-location'],
```

**Comment by felix2056** [comment]
Don't forget to run `php artisan config:cache` after editing `config/geoip`

**Comment by bilogic** [comment]
@tontonAurel 

I think it is better to work with Laravel defaults out of the box, but today, this package keeps throwing `This cache store does not support tagging`. The config line by @tiznull makes sense.

**Comment by bilogic** [comment]
@Torann 

I think it is better to work with Laravel defaults out of the box, but this package currently throws `This cache store does not support tagging`. 

The config line by @tiznull makes sense, I have filed a PR, hope it will be accepted. Thank you.
