### ISSUE TITLE
Calling the geoip functions?

### ISSUE THREAD

**Issue by erkand-imeri** [Torann/laravel-geoip#126]
Hi,

I installed this package in Laravel and i wanted to use it for the project in my work. I need the geoip together with the currency attribute.

I was reading the documentation and couldn't find out a brief description how to import geoip Classes/Functions and call them from Controller or Models.

Any info/step regarding this?

**Comment by Torann** [comment]
You can use the helper `geoip `.

http://lyften.com/projects/laravel-geoip/doc/methods.html
