### ISSUE TITLE
Unable to download database. (Service Temporarily Unavailable)

### ISSUE THREAD

**Issue by d-knafo** [Torann/laravel-geoip#129]
after `php artisan geoip:update`

I get this error: 

`Unable to download database. (Service Temporarily Unavailable)`

**Comment by Torann** [comment]
You need to update your config file with the new URL to the download file. This sometimes changes that is why it is in the config and not hardcoded in the source. The files are found here: https://dev.maxmind.com/geoip/geoip2/geolite2/
