### ISSUE TITLE
Error handling for GeoIp2\Exception\AddressNotFoundException

### ISSUE THREAD

**Issue by jonasva** [Torann/laravel-geoip#13]
I noticed that when an IP is not in the maxmind database an error is thrown "GeoIp2\Exception\AddressNotFoundException". 

Perhaps it's best to catch and log it directly?

**Comment by jonasva** [comment]
Pull request #14

**Comment by Torann** [comment]
Added in version [0.2.0](https://github.com/Torann/laravel-geoip/tree/0.2.0) for Laravel 5
