### ISSUE TITLE
Installation in Laravel 5.7.13 (PHP 7.1.9)

### ISSUE THREAD

**Issue by jiahong96** [Torann/laravel-geoip#131]
Does this package support Laravel 5.7? Am using default ipapi service, however geoip()->getLocation('27.974.399.65'); always return nothing.

**Comment by jiahong96** [comment]
turns out it's returning an array, hence an empty object in my response

**Comment by MrEhsanEllahi** [comment]
Why you closeed this, got your proble resolved?
