### ISSUE TITLE
Allow ipv6

### ISSUE THREAD

**Issue by jonasva** [Torann/laravel-geoip#15]
I noticed that there is no Ipv6 support. 
It's true that there is no city lookup support for ipv6 currently, but country/timezone/continent might still be useful to get. 

I've added a pull request: #14

**Comment by Torann** [comment]
Added in version [0.2.0](https://github.com/Torann/laravel-geoip/tree/0.2.0) for Laravel 5

**Comment by tholu** [comment]
Any plans to backport this for Laravel4?

**Comment by Torann** [comment]
There are directions for this in the README under Laravel 4 Installation :-)

**Comment by tholu** [comment]
Sorry, but I can't seem to find it or I don't get it. This should be the README for Laravel 4? https://github.com/Torann/laravel-geoip/tree/0.1.1
IPv6 is not mentioned here.

PS: The link "GeoIP for Laravel 4 on GitHub" on the linked page points to https://github.com/torann/laravel-hashids

**Comment by Torann** [comment]
Ah sorry. That was my fault. I thought you wanted to install this in a Laravel 4 Installation, so I pointed you to the directions for that.

There aren't any plans to backport the IPv6 feature. Sorry.
