### ISSUE TITLE
Undefined method reference...

### ISSUE THREAD

**Issue by PhoenixPeca** [Torann/laravel-geoip#152]
Hi,

I would just like to point out a reference to a method that does not (or no longer) exists..

https://github.com/Torann/laravel-geoip/blob/d00e9b5b9c8e9c79c47fc4d78d4b47db1cd532c3/src/GeoIP.php#L164

![image](https://user-images.githubusercontent.com/9730242/64440590-cf516780-d0fe-11e9-9a45-e2c787f44fc1.png)

Possible fix: https://github.com/Seldaek/monolog/commit/d686f25f6c1ce9706e23cf1c6f97c76e8bf83d09

**Comment by imami** [comment]
This is because `addError` method no longer exists in  [Monolog](/Seldaek/monolog) v. 2.0.
Maybe some major upgrade in [laravel-geoip](/Torann/laravel-geoip) is needed!

@Torann

**Comment by PhoenixPeca** [comment]
Correct me if I'm wrong, but as I can see, the only usage of monolog in this repo is found in these lines:
https://github.com/Torann/laravel-geoip/blob/dc3c4fc17779b3521736dd4e04d1fa2dd8f55db9/src/GeoIP.php#L162-L164

so, i dont think a major upgrade is needed.. I have made a PR already for this: #153

**Comment by imami** [comment]
@PhoenixPeca You're correct

**Comment by Torann** [comment]
Looks like `addError()` just needs to be changed to `error()`.

I'm also 100% fine with dropping the logger from here. I never use it.

**Comment by Torann** [comment]
LOL I just saw that you made the changes and put up a PR @PhoenixPeca. I'll merge it now 👍

**Comment by Torann** [comment]
Hold up. This change is breaking. I'll make a comment on the PR for a fix to prevent this

**Comment by Torann** [comment]
Ok. I just looked, v1.x of Monolog also has the method `error`, so this will not break anything. Merging now :-)
