### ISSUE TITLE
Maxminddb library search tree corrupt

### ISSUE THREAD

**Issue by RFreij** [Torann/laravel-geoip#167]
laravel-geoip version: 1.1.0
Laravel version: 5.5

Hi,

We are currently experiencing a problem when updating the maxminddb library with the command geoip:update. When using the command the file seems to be corrupt, however when downloading the file directly from the maxmind server the file works. 

We found out about this problem when we noticed content was visible that shouldn't have been visible for countries like Belgium.

We've been testing what could be wrong using a PC with Ubuntu installed and used the following command:

` mmdblookup --file ./geoip.mmdb --ip 185.104.186.184`

The error we got is: 

`Got an error from the maxminddb library: The MaxMind DB file's search tree is corrupt`

**Comment by edtsz** [comment]
Hello,
I'm getting the same problem.

```
laravel 5.8.36
laravel-geoip 1.1.0

update_url: https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&suffix=tar.gz&license_key=<MY_LICENSE_KEY>
```

**Comment by michaelanting** [comment]
Hello,

We also had this issue, it was resolved for us after we upgraded to Laravel 6.0. I'm not sure if the Laravel update itself fixed the issue. Just leaving it here as a possible solution.

**Comment by edtsz** [comment]
Hi guys,
My problem disappeared. I just update all packages with ```composer update```, now Laravel 5.8.37 is running.

**Comment by RFreij** [comment]
Like @michaelanting said it apears to be working again after updating to Laravel 6.0. @edtsz good to head updating to the latest patch of 5.8 is working to :) 

I'll close this issue for now, hope it doesn't happen again.
