### ISSUE TITLE
IP returning not found, but maxmind code working

### ISSUE THREAD

**Issue by donenvy** [Torann/laravel-geoip#17]
Tried using this, got it all installed and thought it was working ok. When I tried a near by IP address it came up as not found. So I tried the other plugin I had installed https://github.com/smalldogs/ip2country
noticed it recognized the IP address. So i went ahead and installed maxmind directly https://github.com/maxmind/GeoIP2-php to see what happens and even this identifies the correct country code, I have pointed both this plugin and maxmind to use the same mmdb file, so can't understand why maxmind finds it, yet here it does not. Yet it works on other IP's. Is there some other filtering taking place on this plugin that is excluding the IP in question?

**Comment by Torann** [comment]
Give version [0.2.0](https://github.com/Torann/laravel-geoip/tree/0.2.0) a try. Keep in mind if is for Laravel 5. 

Laravel GeoIP was using an older version of the GeoIP2-php library, this was updated in v0.2.0

**Comment by avspro** [comment]
Hi,

Why do you think that 1.0.0.0/32 and 2.0.0.0/32 networks are reserved (from /src/Torann/GeoIP/GeoIP.php > $reserved_ips)? I'm almost sure that these are public IPs.

**Comment by avspro** [comment]
Sorry, I meant 1.0.0.0/8 and 2.0.0.0/8

**Comment by Torann** [comment]
The reserved ip list is removed in v1.0 and in it's place it uses PHP's filters
