### ISSUE TITLE
Laravel 5 support?

### ISSUE THREAD

**Issue by mendrinos** [Torann/laravel-geoip#18]
Is there any plan to support Laravel 5?

**Comment by Torann** [comment]
Sure is. I'll be working to upgrade all of my sites to Laravel 5 in the coming weeks. So there should be an soon.

**Comment by grindmodeon** [comment]
+1 for this also!

**Comment by diridam** [comment]
+1. looking forward!

**Comment by grindmodeon** [comment]
Any idea when this will be done?

**Comment by Torann** [comment]
Working on it now :-)

**Comment by Torann** [comment]
Laravel 5 now supported in version 0.2.0:

```
"torann/geoip": "0.2.*@dev"
```
### Changes:

**v0.2.0**

- Update to Laravel 5
- Support IPv6
- Log address not found exceptions
- Supports a custom default location
