### ISSUE TITLE
Support MaxMind country database

### ISSUE THREAD

**Issue by tholu** [Torann/laravel-geoip#19]
It would be great if this extension would support the usage of only the MaxMind country database as well (also for the Laravel 4 version), since the commercial version of it is much cheaper than the city database.

**Comment by lpil** [comment]
:+1:

**Comment by MarkBlah** [comment]
Yep Agreed!

**Comment by lpil** [comment]
I've just started using the official MaxMind library.

**Comment by Torann** [comment]
The Laravel 4 version is no longer maintained

**Comment by AidasK** [comment]
This issue is not related with laravel 4 and MaxMind country database support would be nice
