### ISSUE TITLE
Non-static method Torann\GeoIP\GeoIP::getLocation() should not be called statically, assuming $this from incompatible context

### ISSUE THREAD

**Issue by opheliadesign** [Torann/laravel-geoip#20]
Attempted to use this several different ways. Do I need to sign up for an external account in order to use this? Not very clear from the documentation - not sure if maxmind is optional or required. I also see that another issue was posted with the same error.

Here is my test:
```
// Routes.php
use Torann\GeoIP\GeoIP;
Route::get('geoip', function() {
	$location = GeoIP::getLocation();
});
```

**Comment by davidsarkany** [comment]
Try:

use Torann\GeoIP\GeoIPFacade as GeoIP;

Route::get('geoip', function() {
    $location = GeoIP::getLocation();
});

**Comment by mydnic** [comment]
I confirm that @davidsarkany solution solves the problem
Thanks

**Comment by hakobfromlightin** [comment]
@davidsarkany solution didn't work for me, however I just used Facade:

"use Torann\GeoIP\GeoIPFacade as GeoIP"
$location = GeoIP::getLocation();

and this worked perfectly

**Comment by m7vm7v** [comment]
sdfsdfs

**Comment by m7vm7v** [comment]
I have tried everithing but still have the same problem.
I have tried with

$geo = new GeoIP();
$geo - getLogation();

but after that I have got "Argument 1 passed to Torann\GeoIP\GeoIP::__construct() must be an instance of Illuminate\Config\Repository, none given"

so I am missing the arguments for the __construct ....$config, $session 
so it should be looking like this

$loc = new GeoIP($config, $session);
$loc ->getLocation();

but what do I need to give to $config = ? and $session = ?

**Comment by pratik007kumarDev** [comment]
i am geting following result
line no Array
(
    [ip] => 112.133.232.11
    [isoCode] => IN
    [country] => India
    [city] => 
    [state] => 
    [postal_code] => 
    [lat] => 20
    [lon] => 77
    [timezone] => Asia/Kolkata
    [continent] => AS
    [default] => 
)
but i need city ?
.....pls anybody guide me and help me to find city and state

**Comment by Dragas** [comment]
Can confirm.
GeoIPFacade::getLocation() does not return City, State and postal code.

**Comment by 7skyzahid** [comment]
I am facing the same problem as @m7vm7v has. Please help us out

**Comment by Torann** [comment]
Did you follow the [Get Started](http://lyften.com/projects/laravel-geoip/doc/) guide? Because @m7vm7v did not. The `\Torann\GeoIP\GeoIPServiceProvider::class` is what creates the GeoIP instance that is used for the facade and helper function.

**Comment by Torann** [comment]
As for City, State, and postal code, if they aren't available for the given IP then they won't be included in the returned object.
