### ISSUE TITLE
Not working at Laravel 8 

### ISSUE THREAD

**Issue by ivanradojevic-web-dev** [Torann/laravel-geoip#204]
```
geoip()->getLocation($id);
```
return empty string

**Comment by ngocnd0242** [comment]
@ivanradojevic-web-dev `$id` seems wrong, I thinks it's ip address. Please show more details, anyone can help you?

**Comment by ivanradojevic-web-dev** [comment]
> @ivanradojevic-web-dev `$id` seems wrong, I thinks it's ip address. Please show more details, anyone can help you?

Something else was the problem, It is working!
