### ISSUE TITLE
Works fine in webpage but not works in api response

### ISSUE THREAD

**Issue by vadimwe** [Torann/laravel-geoip#208]
Works fine in webpage but not works in api response.
Is it possible to use it in api with api middleware?

**Comment by vadimwe** [comment]
any ideas?

**Comment by Cod3rMax** [comment]
it works great for me, can you post more information on the errors that you have?

**Comment by vadimwe** [comment]
No errors in logs or in runtime. Just empty object.

`return response()->json([
    		'status' => 1,
                'geoip' => geoip()->getLocation()
    	]);`

I`m confused. Same code works fine with blade response

**Comment by Cod3rMax** [comment]
Just today i did develop a package for proxy checking that requires `geoip` and it works perfectly with me.
So what i can see in your code maybe you want to get the location or something? how about this:

`return response()->json(geoip('IP here')->toArray(), 200);`

This will return for you all the data, from it you can select whatever you want for example the location:

`return response()->json(geoip('IP here')->country, 200);`

i hope this fix your problem.

**Comment by vadimwe** [comment]
@Cod3rMax big thanks for your help.

`'geoip' => geoip()->getLocation()->toArray(),` works excellent. 

response()->json() should convert object properties to array automatically but seems not in this case.

**Comment by Cod3rMax** [comment]
yep i think if you want it to convert it to array automatically you need to add getData() at the end i did not test it, anyway glad to help have a great day :)

**Comment by vadimwe** [comment]
`geoip()->getLocation()->toArray()` works perfect.

Have a great day too!
