### ISSUE TITLE
Need other location data such as Region

### ISSUE THREAD

**Issue by mirzabusatlic** [Torann/laravel-geoip#22]
`getLocation()` is returning only some data. What if I want something more specific, like `$record->mostSpecificSubdivision->name`?.

**Comment by kyranb** [comment]
The idea is just an IP address converted to a location.

What further specific detail would you already have available that you need
to store?

Otherwise a normal database query be able to store any future detail you
want.

**Comment by mirzabusatlic** [comment]
Take a look at `GeoIP.php`:

```php
        try {
            $record = $maxmind->city($ip);

            $location = array(
                "ip"			=> $ip,
                "isoCode" 		=> $record->country->isoCode,
                "country" 		=> $record->country->name,
                "city" 			=> $record->city->name,
                "state" 		=> $record->mostSpecificSubdivision->isoCode,
                "postal_code"   => $record->postal->code,
                "lat" 			=> $record->location->latitude,
                "lon" 			=> $record->location->longitude,
                "timezone" 		=> $record->location->timeZone,
                "continent"		=> $record->continent->code,
                "default"       => false
            );
        }
```

The `$record` variable actually has a lot more information, including something like `$record->mostSpecificSubdivision->name` that I want to be returned. There's no way I can grab that information 
because `$location` is being returned instead of `$record`.
