### ISSUE TITLE
Double ip address not returning proper location

### ISSUE THREAD

**Issue by rickshawhobo** [Torann/laravel-geoip#25]
Hello
After much debug I discovered that my server is returning a double ip address for the remote ip. The remote ip looks like xxx.xxx.xxx.xxx, yyy.yyy.yyy.yyy and the resulting location is returned with default => 1

The double IP is coming from an apache config involving reverse proxy and I have no control over it. Perhaps the package could account for it and just take the first ip?

**Comment by kyranb** [comment]
Any reason why this package needs that functionality? Are you able to parse the ip address  yourself, then call getLocation() with that ip address?

**Comment by rickshawhobo** [comment]
The reason I use a package is for convenience. Yes I could parse the ip myself and specify it, but then I can also just call the maxmind api myself. If double ip's are common enough (apparently they are - I never realized) then maybe the package can just handle it. It's an easy and safe change.

**Comment by kyranb** [comment]
I can't say that I've ever come across double ip addresses before. I agree that if they are commonly used, it would make sense to automatically account for them.

**Comment by tremby** [comment]
It'll look like that in some cases when a chain of addresses is available, for instance when behind a proxy or load balancer.

**Comment by king724** [comment]
This is happening to me behind a CDN. I've seen it return up to 4 IPs in a comma seperated list. The first one is always the one I want.

**Comment by Torann** [comment]
Give [v1.0.2](https://github.com/Torann/laravel-geoip/releases/tag/1.0.2) a try

**Comment by king724** [comment]
@Torann works great for me, thanks!

**Comment by Torann** [comment]
Good to hear :-)
