### ISSUE TITLE
Zipcode to Lat/Lng

### ISSUE THREAD

**Issue by m-a-n-g-o** [Torann/laravel-geoip#28]
Is it possible to go from Zipcode to Lat/Long?

**Comment by cringer** [comment]
Please explain.  You do a lookup by the IP and the record containing the values are returned.  The lookups are not done by Zipcode.

**Comment by chicag0** [comment]
Can you lookup a zipcode and get lat/lng returned rather than using an IP to search

**Comment by cringer** [comment]
The API for searching the Maxmind BIN database from this package is GeoIP2 (https://github.com/maxmind/GeoIP2-php).  There is no method for looking up data by zip code.
