### ISSUE TITLE
Non-static method Torann\GeoIP\GeoIP::getLocation() should not be called statically, assuming $this from incompatible context [php 5.5.10]

### ISSUE THREAD

**Issue by roelvan** [Torann/laravel-geoip#3]

**Comment by 7skyzahid** [comment]
$ip = $_SERVER["REMOTE_ADDR"];
        $location = GeoIP::getLocation($ip);
        dd($location);
I am facing the same error Sir

**Comment by Torann** [comment]
Did you follow the [Get Started](http://lyften.com/projects/laravel-geoip/doc/) guide? And are you using Laravel? I would suggest looking over the guide http://lyften.com/projects/laravel-geoip/doc/
