### ISSUE TITLE
Check ip logic is returning false

### ISSUE THREAD

**Issue by rajangupta24** [Torann/laravel-geoip#33]
CheckIp function is returning false in case ip = 1.39.45.208

And which shouldn't happen. Tell me how to fix this.

     private function checkIp($ip)
	{
		if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV4)) {
			$longip = ip2long($ip);

			if (! empty($ip)) {
				foreach ($this->reserved_ips as $r) {
					$min = ip2long($r[0]);
					$max = ip2long($r[1]);
					if ($longip >= $min && $longip <= $max) {
						return false;
					}
				}

				return true;
			}
		} else if (filter_var($ip, FILTER_VALIDATE_IP, FILTER_FLAG_IPV6)) {
			return true;
		}

**Comment by cringer** [comment]
I'm not 100% sure about this methods intention.  However, on my development branch on my fork I had modified this function and this IP checks out.  I will check to see if I can reproduce on this Torann's current release.

**Comment by Torann** [comment]
The `checkIp` method has been rewritten in v1.0, see if that fixes it for you. I plan to release v1.0 as soon as my documentation is complete.
