### ISSUE TITLE
Compatible with laravel 5.1

### ISSUE THREAD

**Issue by nardev** [Torann/laravel-geoip#34]
is is something up to me, i can't get it to work with L5.1?

**Comment by dlaynes** [comment]
Providers:
````
Torann\GeoIP\GeoIPServiceProvider::class,
````

Aliases:
````
'GeoIP' => Torann\GeoIP\GeoIPFacade::class,
````

**Comment by DTaylor925** [comment]
I keep trying this with Orchestra Platform, but am getting this error.
 [ErrorException]                                                                                                                                                                                                                                       
Argument 1 passed to Torann\GeoIP\Console\UpdateCommand::__construct() must be an instance of Illuminate\Config\Repository, instance of Orchestra\Config\Repository given, called in /Users/davidtaylor/Sites/citgo-location-platform/vendor/torann/geoip/src/Torann/GeoIP/GeoIPServiceProvider.php on line 42 and defined                                                                                                                                                                                  
Found this about it
https://laracasts.com/discuss/channels/general-discussion/trying-to-access-config-values-from-package-service-provider

which would lead to this:

https://laracasts.com/discuss/channels/general-discussion/common-tasks-and-variables                                           

Any suggestions on what I could do as a workaround for now?

**Comment by cringer** [comment]
nardev,

Those are the correct lines for Laravel 5.1.  Are you still having issues?

**Comment by cringer** [comment]
DTaylor925,

As Orchestra Platform is using a modified Laravel filestructure you would need to inquire with them.

**Comment by DTaylor925** [comment]
Yeah, so since Orchestra utilizes a child class of Illuminate\Config\Repository, I had to more or less make a workbench/local copy of this package and make everything that used the Repository Class extend from Orchestra\Config\Repository.  Breaks the upgrade path for this package in this particular project, but I did get it working.

Thanks!

**Comment by Torann** [comment]
I all of my projects I have been moving away from using the `Illuminate\Config\Repository` instance for config settings. In v1.0 this is completely removed.

**Comment by nardev** [comment]
To close this a?

**Comment by Torann** [comment]
Are you asking why I closed this? v1.0 doesn't use the `Illuminate\Config\Repository` instance, nor is this meant for or tested on Orchestra

**Comment by nardev** [comment]
@Torann no no, i meant it should be closed!

**Comment by Torann** [comment]
Ah okay. :-)
