### ISSUE TITLE
Support IP2Location LITE

### ISSUE THREAD

**Issue by m-cameron** [Torann/laravel-geoip#36]
@Torann

Do you have plan to support the IP2Location LITE database? It has the ZIP code information which is an advantage compare to GeoIP.

http://lite.ip2location.com

**Comment by canfiax** [comment]
+1

**Comment by cringer** [comment]
Based on the composer.json it looks like infoDb was planned.  This uses the ip2location lite database but is a SaaS API service.  I am not 100% sure of the devlopers intention so hopefully he gives us an update soon.

**Comment by Torann** [comment]
It was planned, but was dropped. Sorry for the confusion. In v1.0 you have the ability to create new services. You might want to give that a try when it comes out
