### ISSUE TITLE
Anonymous IP returning everything NULL

### ISSUE THREAD

**Issue by donenvy** [Torann/laravel-geoip#38]
ran across an IP address which returned no country code neither a default location. After investigation I found out why. On maxmind the IP is down as a anonymous IP address without a geoname_id code. Hence the IP a default location was not returned as the IP was found in the database but with no geo code.  Hence everything returned was null instead of default location or an identifier for anonymous IP.

Could you advise on the L4 version what to add to take these anonymous IP's into account instead of returning everything NULL

**Comment by Torann** [comment]
This seems to be on maxmind's end. I could just do a check on your end before using the data
