### ISSUE TITLE
Wrong location

### ISSUE THREAD

**Issue by sojic** [Torann/laravel-geoip#51]
Shortly:
`>>> \GeoIP::getLocation('2.54.143.99');
=> [
     "ip" => "127.0.0.0",
     "isoCode" => "US",
     "country" => "United States",
     "city" => "New Haven",
     "state" => "CT",
     "postal_code" => "06510",
     "lat" => 41.31,
     "lon" => -72.92,
     "timezone" => "America/New_York",
     "continent" => "NA",
     "default" => true,
   ]
>>> 
`
Returns "default" location

While another script (not Laravel)
`require  "geoip-maxmind/geoipcity.inc.php";
//require  "geoip-maxmind/geoipregionvars.php";
$gi = geoip_open("geoip-maxmind/1_GeoLiteCity.dat", GEOIP_STANDARD);
$gr = geoip_record_by_addr($gi, $IP);
if(!empty($gr->city)) {
	$gr->country_name = utf8_encode($gr->country_name);
	$gr->city = utf8_encode($gr->city);
	echo "{$gr->city}, {$gr->country_name}\n";
} elseif(!empty($gr->country_name)) {
	$gr->country_name = utf8_encode($gr->country_name);
	echo "{$gr->country_name}\n";
}
`
Returns Israel (which is correct).

**Comment by sojic** [comment]
You have "Reserved IP addresses" with range: array('0.0.0.0','2.255.255.255')???? 

Private IP ranges:
10.0.0.0 - 10.255.255.255
172.16.0.0 - 172.31.255.255
192.168.0.0 - 192.168.255.255

**Comment by Torann** [comment]
Reserved IP addresses have no location and aren't valid in the GeoIP database that's why they are there.

But in v1.0 the "Reserved IP addresses" have been dropped and now it uses `filter_var`. But you'll probably still get the same result.

**Comment by akshaymirackle** [comment]
Facing same issue. "103.66.96.83" this is Indian IP address, but showing China instead.

Torann\GeoIP\Location Object
(
    [attributes:protected] => Array
        (
            [ip] => 103.66.96.83
            [continent_code] => AS
            [continent_name] => Asia
            [country_code2] => CN
            [country_code3] => CHN
            [country_name] => China
            [country_capital] => Beijing
            [state_prov] => Tianjin
            [district] => 
            [city] => 
            [zipcode] => 
            [latitude] => 39.10956
            [longitude] => 117.22337
            [is_eu] => 
            [calling_code] => +86
            [country_tld] => .cn
            [languages] => zh-CN,yue,wuu,dta,ug,za
            [country_flag] => https://ipgeolocation.io/static/flags/cn_64.png
            [geoname_id] => 6527845
            [isp] => Yuanwang Technology (Tianjin) Co. Ltd.
            [connection_type] => 
            [organization] => Balaji Services
            [currency] => Array
                (
                    [code] => CNY
                    [name] => Yuan Renminbi
                    [symbol] => ¥
                )

            [time_zone] => Array
                (
                    [name] => Asia/Shanghai
                    [offset] => 8
                    [current_time] => 2021-08-06 20:26:21.880+0800
                    [current_time_unix] => 1628252781.88
                    [is_dst] => 
                    [dst_savings] => 0
                )

            [default] => 
        )

)
