### ISSUE TITLE
Making a Peanut Butter & Jelly Sandwich

### ISSUE THREAD

**Issue by adamKDean-zz** [Torann/laravel-geoip#53]
Just because I am an experienced developer that is now attempting to learn the Laravel coding style... I though I would drop a quick line in regards to the documentation. It probably seems painfully obvious to a lot of people who have been developing with Laravel over the years, however, installing the repo and following the instructions in the readme file was giving me a class not found error. Then I noticed that the error was because Laravel was attempting to look for a GeoIP controller because I had failed to "use GeoIP;" at the top of my controller definition.

So, just for the sake of "idiot-proofing" some things and being clear, might want to explicitly add that to the installation instructions.

**Comment by kyranb** [comment]
Just a heads up, that's due to PHP's name spacing, not this package.
