### ISSUE TITLE
Use Request facade instead of $_SERVER

### ISSUE THREAD

**Issue by Cardy** [Torann/laravel-geoip#54]
Hello,
I've noticed that using GeoIP::getLocation() without parameters return the default location if the web server sits behind a proxy.
If I use\GeoIP::getLocation(Request::ip() instead I get the right result. Request is Illuminate\Support\Facades\Request.
I suppose it works fine because internally Request object checks for X-Real-IP X-Forwarded-For and other stuff like this before returning ips.

Regards,
Andrea

**Comment by Torann** [comment]
I would recommend just using `GeoIP::getLocation(Request::ip())` for this then.
