### ISSUE TITLE
Make saving to session optional

### ISSUE THREAD

**Issue by robjbrain** [Torann/laravel-geoip#56]
Would it be possible to make saving to session optional?

If you're trying to test by switching with a VPN or something there's no way to clear that data without clearing all cookies/sessions.

**Comment by Torann** [comment]
In version 1.0, I added a check that makes sure the stored IP is the same as the one being looked up. If they are the same then it will just return the stored version, otherwise it will look up the new IP. This would seem to fix your issue, right?

**Comment by Torann** [comment]
Caching is completely optional now
