### ISSUE TITLE
Always returning NULL (DEFAULT)

### ISSUE THREAD

**Issue by vadimwe** [Torann/laravel-geoip#58]
Laravel 5.2 Latest 

"geoip2/geoip2": "^2.4",
"torann/geoip": "^1.0"

**Comment by MrEhsanEllahi** [comment]
![image](https://user-images.githubusercontent.com/37433424/57175816-9875f700-6e69-11e9-83df-6807730e0639.png)

I am using laravel 5.8, and using this code in my homecontroller but it always returns default value. Site is live
