### ISSUE TITLE
Unresolvable dependency resolving ... in class Torann\GeoIP\GeoIP

### ISSUE THREAD

**Issue by alariva** [Torann/laravel-geoip#62]
Hi,

After upgrading to `1.0.2` (btw, nice changes so far to see), I'm getting this error during tests:

`Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class Torann\GeoIP\GeoIP`

I've followed the [upgrade guide](http://lyften.com/projects/laravel-geoip/doc/upgrade.html), however I'm pretty sure I'm missing something.

I'm running Laravel 5.2 and you may find the current state of my project ([broken](https://travis-ci.org/timegridio/timegrid/builds/168729839#L685)) [in this branch](https://github.com/timegridio/timegrid/tree/upgrade/geoip)

Thanks in advance for your support!

**Comment by Torann** [comment]
Sounds like you aren't calling GeoIP correctly. If you are using the facade you need to update your `config/app.php` file to the new namespace:

```php
'GeoIP'      => \Torann\GeoIP\Facades\GeoIP::class,
```

Also here https://github.com/timegridio/timegrid/blob/b45513ed851e6b3b3aa1f9b11d8d9a8ae00e219f/app/TG/DetectTimezone.php#L13 should look more like this:

```php
    public function __construct()
    {
        $this->geoip = app('geoip');

        $this->detect();
    }
```

You can also use the helper function `geoip()` to get the GeoIP instance.

**Comment by alariva** [comment]
Thanks @Torann for the hints. 

For the record:
So I got the production code [changed as well as tests](https://github.com/timegridio/timegrid/commit/93e3079fd5ffc4878c19bacf7982b0f865fbf8e5), and I'm not sure if I'm getting this the way it should be, but having the tests pass seem to be a good starting point.

https://travis-ci.org/timegridio/timegrid/builds/168768522
