### ISSUE TITLE
Json encoding of Torann\GeoIP\Location

### ISSUE THREAD

**Issue by nikolaynesov** [Torann/laravel-geoip#65]
Json encoding of Torann\GeoIP\Location returns empty string. 
Expected: json encoded attributes.

**Comment by nikolaynesov** [comment]
quick and dirty workaround would be
`json_encode(array_values((array)geoip()->getLocation())[0])`

**Comment by allan-empalmado** [comment]
If using Laravel this also works `Response::json(geoip()->getLocation()->toArray());`

**Comment by rehanshaikh1823** [comment]
$location = GeoIP::getLocation();
 $locationArray = $location->toArray();
 $jsonData = json_encode($locationArray);
dd($jsonData);
