### ISSUE TITLE
Doesn't work with paid GeoIP Country DB

### ISSUE THREAD

**Issue by selfpaidinc** [Torann/laravel-geoip#69]
I use this to find visitor country on my web application, I purchased the paid GeoIP Country DB as that's all I needed, I didn't realize this used the City DB. Any way to support just Country?

**Comment by sandeesh-s** [comment]
The package facilitates writing custom services. You can have a look at https://github.com/Torann/laravel-geoip/blob/master/src/Services/MaxMindDatabase.php and extend this to support country only database. Then set the correct class in the config file at https://github.com/Torann/laravel-geoip/blob/master/config/geoip.php#L55.
