### ISSUE TITLE
A few basic questions

### ISSUE THREAD

**Issue by javisperez** [Torann/laravel-geoip#70]
Hello, i dont know if an issue is the best place to ask these questions but i have no idea where else i could do, so, sorry if shouldn't be here :)

1.  Do i need to have an account on ip-api.com or maxmind api to use this? i mean, can i use the .mmdb only? like download the db and read it from there?
2. I've tried the artisan geoip:update command but says that only continents were updated, so, not sure what that means, is that command for update the db?
3. If can be used without the api, do i need to download the mmdb by my own or the library downloads it? i see in the config a "update_url" entry but also a "database_path" so i dont know if the library downloads it from the update_url and then move it to the database_path or do i have to place it there by my own?

Those might be dumb questions i'm sorry, im just not clear enough.

Thank you!

**Comment by javisperez** [comment]
Nevermind! found the answers in the docs (shame on me!), so, in case anybody has the same questions, here are the answers:

1. Yeah, just change the config like this:
```
'service' => 'maxmind_database',
```
2. It was on ipapi service, if  using **maxmind_database**, first run:
```
composer require geoip2/geoip2
```
and then run the update, should work
3. This library downloads it, and the doc even suggests running the geoip:update command in the build (which is a great idea)

Sorry for the question, i missunderstood the doc the first time, a 3rd read was enough to catch it up :).

Great library btw!

**Comment by youngbobby** [comment]
Hi @javisperez 

I know this is closed and you probably figured your way around the package but I would be glad if you could help me with some issues I'm facing.

I have followed the guide carefully and I still get the default response when I call the `getLocation()` method.

My configuration: 

I'm running on Heroku (I'm not sure if it affects storage files in any way)

**config/geoip.php:**

   `'service' => 'maxmind_database',`

**Composer.json**

        "post-update-cmd":[
            "php artisan geoip:update"
        ]

**Problem:**

I still get the default response :(

Thanks in advance for responding.
