### ISSUE TITLE
This cache store does not support tagging

### ISSUE THREAD

**Issue by evrard-c** [Torann/laravel-geoip#89]
I'm using a file cache driver.
After reading that 

> "Cache clearing requires Cache Tags, so is not supported when using the file or database cache drivers."

, i opened `config/geoip.php` and changed `'cache' => 'all'` to `'cache' => 'none'`
In my understanding I thought this would disable the use of the cache, but when I try to open a test page using the package I still have this error: `This cache store does not support tagging`
Does this mean that it is impossible to use the package when you do not have a cache driver with cache Tags ?

**Comment by baljeetsidhu** [comment]
@evrard-c I am facing same issue.

For now, commented out line `'cache_tags' => ['torann-geoip-location'],` and it works.

**Comment by evrard-c** [comment]
Thanks @baljeetsidhu , this solved the problem.
