### ISSUE TITLE
What's next?

### ISSUE THREAD

**Issue by robertnicjoo** [Torann/laravel-geoip#97]
Hi,

I just installed this package on my application and I have no idea how to use it!

## Here is what I want:

I want save user **IP** and **ISO_CODE** in database so I can use it in my chart as visitors location. that's all I need from this package.

_PS: I want get user **IP** and **ISO_CODE** in any page user visits and not just in my posts or categories etc pages._

Anyone can help with that?

**Comment by abdulahkam** [comment]
I think it is pretty clear in the [documentation](http://lyften.com/projects/laravel-geoip)

**Comment by robertnicjoo** [comment]
@abdulahkam i didn't find it pretty clear that's why i asked this question, otherwise i wouldn't.

for example which part of documents pointed if i need to create middleware or anything else in order to get users ip in specific url or every url in my website?

please if you have/know the solution of my issue provide it otherwise just wasting our times both!


kindly regards to you and your opinion.
